version: '3.9'

services:
  todo:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./todo
    ports:
      - "8000:8000"
    networks:
      - microservices
      
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8080:8080"
    depends_on:
      - todo
    
  login:
    build:
      context: ./login
    ports:
      - "8001:8001"
    networks:
      - microservices
    volumes:
      - static:/static

  client:
    build:
      context: ./client
    ports:
      - "8002:8002"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  static: