version: '3.9'

services:
  todo:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./todo
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - microservices
    
  login:
    build:
      context: ./login
    ports:
      - "8001:8001"
    networks:
      - microservices
    volumes:
      - static:/static

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  static: